* Requirements

We will occasionally need to reprocess events in the case of schema changes, bug fixes, etc. A clear and consistent method for doing this is necessary.

It would be convenient if this workflow were incorporated into testing as well, this way the effect of code changes would be tested using the same mechanism used to bring them into effect in production.

* Products
** Gene Validity GKS
Fully GKS compliant 
* Discussion

I want to test components of the system I'm working on, in parallel, across the entire input set, one operation at a time.

This translates into testing one interceptor at a time; being able to feed it the context it needs, and testing the outcomes. Speed up the feedback loop.

At the end of the day, the business logic really needs to be a pure function.

And it is--until we get to the versioning stuff.

I think it's possible that we can store the various intermediate products; instructions to skip them can be processed on message reprocessing.

If I do local reprocessing, I'm going to need a mechanism to make sure that it completes if interrupted.

Should be rare. Could always start from beginning (though don't want to repeat already read local versions...)

There is an init script when starting the transform processor. It checks to make sure that the sepio stream is up-to-date at both ends.

When processing, what do we write?

* Proposed workflow

** Incoming event -- either GCI event or local recuration event

If new event, there should be no preexising anything--does not matter what models we bypass.

If reprocessing event, I will have incremented the version. There should be no existing models of the same version (unless I version the GCI models and the GV models independently. Adds a bit of complexity, but makes reprocessing potentially much faster. (New deployments available in basically minutes.)

Additional complexity vs quick iteration. May honestly choose quick iteration.

Each transformation format has a message version: GCI model, SEPIO model, Website event

For each of these, if the version exists for the current message version, grab that and send it forward into the event, *unless* there's a flag set to force recompute for that particular step.

For each message, the question is: is there a current version of the event sequence [offset, version] (or version, offset)--may be easy to change later.) For reprocessing, one should simply load the current version. For dev, this may depend on what aspect of the model is being tested.

For each published record, there should be a copy of the actual record (

** Reprocessing workflow

Look for current version of record (GCI Model, model, etc)

If present, load and add to model

If absent, process 

At end, need to decide if any publishable artifacts have changed relative to previous version.

If so, publish patch increment.

If not, do not publish patch. Consider how to record that the event is unchanged in the new version for when this operation is repeated (as it will be)

*** Issues

How to record no-op changes. (publish no-op record).

Do we re-read entire history on startup? Do we instead record where things have left off? (yes, but probably sufficient to read set of summary records, rather than reprocessing entire sequence--can revisit)

Should be feasible given the primitives for Kafka topics, but need to make sure local store is fully constructed and up to date before processing new messages. The usual situation will be that the local store is loaded from a snapshot, but need to consider the exceptional cases. (need to construct processor for building output topic, input processor needs to await output processor reporting up to date; can inspect mechanism used to await gene data.

** Dev workflow 

Here I'm generally going to be running a specific step of the workflow. Need to be able to run things to completion, summarize the results, and zoon in on specific events (favors the offset, vesion pattern.)

Ideally this will look as similar as possible to the reprocessing workflow; both get tested at the same time and I get to avoid special cases.

I can put a message in with a 'force reprocess' flag for a given sequence. At that point, any downstream events should be reprocessed too.

* System versioning

Up to this point the GCI model transformation and the SEPIO model transformation have been layered together. If I consider them to be separate parts of the process, it might be easier to iterate over improements to the model, as well as economize on storage.

GCI Model: this depends entirely on pre-model edits and the JSON-LD context file that gets applied.

SEPIO Transform

Version application

Website Event

I'm testing one interceptor at a time.

There might be a HEAD version for development--always gets overwritten?

* Alternatives for republishing events

** Reset consumer group, reprocess topic

Stick with consumer group architecture, keep existing architecture mostly the same. Whenever we want to reprocess messages, stop the transformer, reset the consumer group, then restart the transformer.

Maybe requires changing the least in terms of ingest and reprocessing, no extra coordination needed in the code, but a bit more fiddly on the ops side.

** Recycle data from local storage

Have a simple topic for reading gene validity all. This topic writes to local storage and passes on the event to the transformer topic, which is just a simple queue topic.

On reprocess, the app first pushes all events from local storage to the transformer. Only after this is done does it continue to process new events.

No unnecessary mucking with offsets or re-reading data from Kafka. Might make it easier to wire in other event sources in the future. Possibly offers an easier handle for testing in development. Production requires a bit more coordination; need to gate processing of new GV messages until older messages have been republished.

** Reset local offset, reprocess topic

Since we're tracking the GV offset locally anyway it may be unecessary to use the consumer group for this, except for coordinating producers. If consumers are prepared to handle duplicate messages, this might not be a big deal. Reverting the consumer group requires some manual consumer handling anyway. In case of an automated restart (kubernettes pods recycling), there is a chance (guarantee?) of two transformers operating at the same time, potentially producing duplicate messages if messages arrive during this time. They should be the ssame code and the same message, at least.

* Architecture

Fairly committed to the local storage solution. Kafka consumer groups for per

** Data

*** Sequential IDs

Incoming messages from the GCI have offsets on the topic, which provides a solid id for the messages

Downstream messages don't have this until they exist on the output stream. For this and other reasons offsets probably shouldn't be the message identifier going downstream.

We *do* need a persistent sequence; I need to know the order these messages should be processed in; at least at the key level.

This feels like a reversable choice; this would be mostly private to this system.

Worth noting that semantic versioning will not produce lexographic ordering on its own, which is probably necessary.

**** Timestamp

Consistent and sequential.
IDs will not be consistent in dev

**** GDM + sequence

Ordering first by curation then by sequence. This feels best. We can version internally by sequence, Externally we use semantic versioning (a bit like a github tag)

**** Mirroring original sequence

Will remain consistent with original ordering.

*** GCI Model

This doesn't change as much as the SEPIO model.  When should it be recomputed?

Computing this is also the most expensive operation

*** Summary data

This needs to be derivable from the published, RDF sepio model.

What information do I need in the summary record? Ideally we keep this as brief as possible and mostly easily queriable from the gene validity model.

** Topics

We are discontinuing using consumer groups. This will significantly reduce the complexity of Kafka integration at the cost of possibly duplicating messages on topic. I think the simplicity is worthwhile.

I think I want to continue using the transactional processor. This processor handles a fair bit of the retry logic; using it ensures that messages are delivered in-order or not at all, and will make sure that existing messages are held until retries are successful. The transactional.id also provides another (more useful) gate for dual messages. It should be less possible for duplicate messages.

gene-validity-all
transform-gv

** Storage

rocks: everything persisitent
atom: Might try using this for coordination between producers, though maybe not needed with the appropriate init-fn? Will hold off, but this could be handy

** Processors

*** Recieve gene-validity-message

This processor:
Recieves a message from gene-validity-all

*** Transform gene-validity-message

Standard transformer established up to this point.

Need to decide how to handle output data.

I'd like to have one message with all necessary data. I can either encode this as a nippy message with all the various serializations, I can rely on one serialization, or I can futz together an edn coded message instead. Choosing nippy will mean changing the serialization logic to handle byte arrays; right now everything depends on string serialization.

I'd like to be able to support binary encoding; I need to carefully consider whether I want to spend more time on this now.

**** One message as source of truth

Strongly prefer this. Two options

***** Everything in RDF Model

This seems like the way to go if I don't want to change everything.

***** Write some sort of EDN monstrosity

I think I would want to have nippy available if we went this route

***** Write to cloud storage, kafka event is a reference

**** Reassemble all output messages

This seems intolerable, although if we start bumping up against size limits in Kafka, we might need to make some adjustments.

*** Generate snapshot

Having the snapshot generator in a separate process seems a bit inappropriate at this point. All the relevant data is already stored in this process.  Additionally, we can make snapshot generation occur whenever data is updated, which is a plus.

** Data flow

Officially cutting ties with the consumer group for this transformation. All state to be handled by local storage.

Reading Gene Validity Complete (could even switch back to raw and pre-load existing curations)




* Event Versioning
** Patch release
Event has been previously published.
Need to check if any current code changes have affected the data.
This *should* be as simple as seeing if the current transforma and prior transform are isomorphic.
If so, noop
If not, publish a patch release.
** New event
Calculate new version based on existing knowledge
* Additional support

** EDN->RDF->EDN

Have written code for edn->rdf. Need code for the inverse operation.

Both should be based on a coherent data model and schema.

Maybe this is a bigger problem than I want to solve right now. Should probably revisit it sometime in the future.

* Next steps
** Deployment

Can I just send it now? Do I need anything else?

Send it, consider this a stage deployment.

Send data to new (stage) topics.

** Duplicate descriptions
See GDI1--test for others

** Record accepted failures
Some events will not pass validation due to known issues. These should not come up time and time again on re-validation.

These events failing validation should be considered when extending tests.
** Minor Errors
These are errors affecting a relatively small number of curations. Probably these will be annotated as accepted failures, but this should be noted


*** Disconnected evidence lines
Segregations with no scored variants, but individuals noted in a segregation, seem to generate disconnected segregation evidence lines.

TNNT2 -- HCM -- unclear
*** Unpublish events without prior event
Results in nil website message event (should not send) -- there are only 10 of these, however
** Collection types in JSON-LD frame
Some types in JSON-LD should be expected to be collections, and should be noted as such.
*** demonstrates is colleciton type



** DONE Remove legacy website ID

No reason to maintain this.

Done.  Got rid of it.

** DONE unpack versioning

I've put too much stuff into versioning.

Done. Split changes out.

*** Renaming the proposition

This deserves to be a separate step, either part of the sepio model, or performed shortly after sepio model.

*** adding the changes

*** calculating the version

*** creating a merged model


** store compound events

Need to figure out how I want to store compound events. Seems like we need cloud storage for this; need to keep too many things at once and do not want to put them all on separate Kafka topics. There's too much data (potentially) to cram into a single event.

Could write an output stream with a summary and a link to the cloud file. This seems like a reasonable compromise.

I think we're going to write these to cloud storage. Will just need a procedure to init the database and make sure everything is up to snuff.

** DONE convince myself publishing without the consumer group is going to work

The one guaranteed bit should be the intake, as long as I assume RocksDB writes are reliable enough without a transaction.

This should also commit an event to the output queue (simple queue). This event should also be reliable.

More likely failure modes:

Interruption during processing
Error or failure during send

We need to be able to write a commit record to RocksDB after a record is sent and fully committed.

Is it going to be an issue to resend multiple records (dropping the write once constraint?)

Should I read from the topic to make sure records got written?

Maybe there is a summary topic for this? Lightweight, tied to a Kafka commit (so guaranteed that records get written).

JSON-LD topic
RDF topic
Summary topic
All curation events

Write event summaries to Kafka topic. Make sure all messages in event summaries have been written to Kafka (maybe await up-to-date). Probably not needed for proof of concept, but shouldn't dally on this one either.

Should be able to get away with reading the keys of the incoming messages topic (maybe? -- no)
Should write a smaller summary record for incoming events, so that we don't wind up having to deserialize the entire event on every startup.

** Snapshot generation

Bring in some of the relevant code for snapshot generation.


** Documentation

** API View

** Proband evidence showing up in recent curations

May be matching on probands not rescored in later SOPs, but still lingering in evidence structure

PSEN2 offset 13145

TNNT2 offset 10329 -- this one seems legit, was republished with updated scores; still doesn't show up on website.

** Github issues

Identifying ranges of acceptable values and validating them will help with many of these.

I have some enumerations listed in the documentation--need to work them into the SHACL validation

*** Zygosity #12

Github #12 Inconsistently attached to Proband vs Variant Observation

I feel like I slapped this together without much thought. This deserves a moment of thinking--results in differences between Proband.

Let's plan on doing a time-boxed workup of this one, but may be hard to resolve immediately.

*** Freetext w \n instead of null #11

May be something I can handle in preprocessing. Could be an easy fix.


*** Schema #10

Add domain and range to schema (may be easy)

detectionType (Cohort vs Proband)

Mapping between Genegraph and GCI/Website (can describe ingest from GCI in broad terms, going to ignore the website)

*** Values and column mapping errors in Sex field #9

OtherVariantDetectionMethod appears in sex
UnknownEthnicity appears in sex

*** previousTesting  and previousTestingDescription #8

Not sure about need to explore in GCI

*** ageType and ageUnit fields #7

Seems like this should be another thing we can test against known valuests
