# Remember to delete evidence_level_assertion
prefix gci: <https://genegraph.clinicalgenome.org/r/>
prefix gcixform: <https://genegraph.clinicalgenome.org/r/gcixform/>
prefix cg: <https://genegraph.clinicalgenome.org/terms/>
prefix dc: <http://purl.org/dc/terms/>

construct {
  
  ?classification a cg:Statement ;
  cg:proposition ?proposition ;
  cg:classification ?evidencelevel ;
  cg:contributions ?contribution , ?publishContribution, ?approvalContribution, ?additionalApprovalContribution ;
  dc:description ?description_text ;
  cg:calculatedClassification ?autoEvidenceLevel ;
  cg:specifiedBy ?sopVersion ;
  cg:curationReasons ?curation_reasons ;
  cg:curationReasonDescription ?reasonForChangedScore ;
  cg:direction ?direction ;
  cg:score ?evidencePointsTotal .

  ?contribution cg:contributor ?affiliation ;
  a cg:Contribution ;
  cg:activityType cg:Evaluated ;
  cg:date ?date .

  ?additionalApprovalContribution cg:contributor ?additionalApprover ;
  a cg:Contribution ;
  cg:activityType cg:Approved ;
  cg:date ?date .

  ?approvalContribution cg:contributor ?affiliation ;
  a cg:Contribution ;
  cg:activityType cg:Approved ;
  cg:date ?date .

  ?publishContribution cg:contributor ?affiliation ;
  a cg:Contribution ; 
  cg:activityType cg:Submitted ;
  cg:date ?publishTime .

}
where {
  
  ?proposition a gci:gdm ;
  gci:gene / gci:hgncId ?hgnc . # Adding path to gene to fix bug related to incomplete GDM

  ?classification a gci:provisionalClassification ;
  # TODO evaluate the effect of removing these
  # Removing to attach unpublish action
  gci:approvedClassification true ;
  gci:publishClassification true ;
  gci:autoClassification ?autoEvidenceLevel ;
  gci:alteredClassification ?alteredEvidenceLevel ;
  gci:classificationPoints ?pointsTree .

  OPTIONAL {
    ?classification gci:additionalApprover ?additionalApprover .
    BIND(IRI(CONCAT(STR(?classification), "_additional_approval")) AS ?additionalApprovalContribution ) .
  }

  
  OPTIONAL {
    ?classification gci:curationReasons ?curation_reasons .
  }

  OPTIONAL {
    ?classification gci:evidenceSummary ?description_text .
  }
  
  OPTIONAL {
    ?classification gci:sopVersion ?declaredSopVersion .
  }

  # Per discussion with Gloria, logic to differentiate SOP v 6 and 5
  
  OPTIONAL {
    ?pointsTree gci:segregation / gci:evidenceCountExome ?evidenceCountExome .
  }

  BIND(IF(bound(?evidenceCountExome), cg:GeneValidityCriteria6, cg:GeneValidityCriteria5) AS ?sopVerionFromStructure) .

  BIND(COALESCE(?declaredSopVersion, ?sopVerionFromStructure) AS ?sopVersion) .

  OPTIONAL {
    ?classification gci:reasons ?reasonForChangedScore .
  }

  # Trying this out as a way to accomodate changed score
  # BIND(IF(bound(?reasonForChangedScore), CONCAT(?description_text, "\n", ?reasonForChangedScore), ?description_text) AS ?description) .
  
  OPTIONAL {
    ?classification gci:classificationDate ?classificationDate .
  }

  OPTIONAL {
    ?classification gci:approvalDate ?approvalDate .
  }

  OPTIONAL {
    ?classification gci:approvalReviewDate ?approvalReviewDate .
  }

  BIND(COALESCE(?approvalReviewDate, ?approvalDate, ?classificationDate) AS ?date)

  BIND(IF(?alteredEvidenceLevel = gcixform:NoModification, ?autoEvidenceLevel, ?alteredEvidenceLevel) AS ?evidencelevel) .

  BIND(IRI(CONCAT(STR(?classification), "_contrib")) AS ?contribution ) .

  BIND(IRI(CONCAT(STR(?classification), "_approval")) AS ?approvalContribution ) .
  
  BIND(IRI(CONCAT(STR(?classification), "_publish_contrib")) AS ?publishContribution ) .

  ?pointsTree gci:evidencePointsTotal ?evidencePointsTotal .

  BIND(IF(?evidencelevel IN (cg:Definitive, cg:Strong, cg:Moderate),
	  cg:Supports,
	  IF(?evidencelevel IN (cg:Refutes, cg:Disputes),
	     cg:Disputes,
	     cg:Neutral)) AS ?direction)
  
}
