prefix gci: <https://genegraph.clinicalgenome.org/r/gci/>
prefix gcixform: <https://genegraph.clinicalgenome.org/r/gcixform/>
prefix cg: <https://genegraph.clinicalgenome.org/r/terms/> 
construct {
  ?parent cg:evidence ?child .
}
where {
  ?parent cg:specifiedBy ?parentCriteria .
  ?child cg:specifiedBy ?childCriteria .
  ?parentCriteria gcixform:supportingCriteriaType ?childCriteria .
}
