prefix gci: <http://dataexchange.clinicalgenome.org/gci/>
prefix gcixform: <http://dataexchange.clinicalgenome.org/gcixform/>
prefix cg: <http://dataexchange.clinicalgenome.org/terms/> 
construct {
  ?parent cg:evidence ?child .
}
where {
  ?parent cg:specifiedBy ?parentCriteria .
  ?child cg:specifiedBy ?childCriteria .
  ?parentCriteria gcixform:supportingCriteriaType ?childCriteria .
}
