prefix gci: <https://genegraph.clinicalgenome.org/r/>
prefix cg: <https://genegraph.clinicalgenome.org/terms/>

construct {
  ?classification cg:contributions _:contrib .

  _:contrib cg:agent ?secondaryContributor ;
  cg:role cg:SecondaryContributor .
}
where {
  ?classification a gci:provisionalClassification ;
  gci:approvedClassification true ;
  gci:classificationContributors ?secondaryContributorID .

  BIND(IRI(CONCAT(?affbase, ?secondaryContributorID)) AS ?secondaryContributor) .
}
