prefix gci: <https://genegraph.clinicalgenome.org/r/gci/>
prefix gcixform: <https://genegraph.clinicalgenome.org/r/gcixform/>
prefix cg: <https://genegraph.clinicalgenome.org/r/terms/>

construct {
  ?classification a cg:EvidenceStrengthAssertion ;
  cg:subject ?proposition ;
  cg:contributions ?publishContribution .

  ?publishContribution cg:agent ?affiliation ;
  cg:role cg:Unpublisher ;
  cg:date ?publishTime .

}
where {
  ?proposition a gci:gdm .
  
  ?classification a gci:provisionalClassification ;

  FILTER NOT EXISTS {
    ?classification  gci:approvedClassification true ;
    gci:publishClassification true .
  }

  BIND(IRI(CONCAT(STR(?classification), "_publish_contrib")) AS ?publishContribution ) .
  
}
